### ISSUE TITLE
Filtering and Deleting URL Entity parmeter 

### ISSUE THREAD

**Issue by engharb** [s9e/TextFormatter#103]
@JoshyPHP 
I want to filter urls in case they belongs to different domains than i.e abc.com --then--> delete this URL.

Is that possible?

Or for such example [url=http://mmm.com][img src="sssss"][/img][/url] remove the url?

regards,

**Comment by JoshyPHP** [comment]
Probably, but I don't know what you mean. BBCodes have attributes, attributes can be modified and invalidated with [attribute filters](https://s9etextformatter.readthedocs.io/Filters/Attribute_filters/). If the filter returns `false` the URL will be invalidated.

Each BBCode has its own attributes, each attribute is filtered separately.

**Comment by engharb** [comment]
@JoshyPHP 
for example:
1- [URL]nnn.com[/URL] ==> I want to be printed/render as text == 'nnn.com'

2- [URL]abc.com[/URL] ==> I want to be rendered as <a> correctly

Is that possible? if yes could you write me a sample code?


regards

**Comment by JoshyPHP** [comment]
I think I already did [in that other comment](https://github.com/s9e/TextFormatter/issues/102#issuecomment-416281651), you just need to change the regexp. I assume you can do that yourself; If you can't, it may be that you need a more entry-level solution.

With that said, there's already a built-in way to [restrict hosts globally rather than on a per-tag basis]https://s9etextformatter.readthedocs.io/Filters/URL_features/Whitelist_hosts/).

**Comment by engharb** [comment]
Also When I have such element [url=http://mmm.com][img src="sssss"][/img][/url]
I want to filter the content which is in our case [img] and if it is not a TEXT then remove [url] or [img].

**Comment by JoshyPHP** [comment]
The library never *removes* content or markup. I don't know what you mean exactly but that doesn't sound like something that can be done at the library level.

**Comment by engharb** [comment]
@JoshyPHP 
you are right, I worked around REGEXP and I fixed the problem.

Thanks a lot.
