### ISSUE TITLE
Error when BBCode is enabled after Autolink/Autoemail

### ISSUE THREAD

**Issue by tobscure** [s9e/TextFormatter#11]
Easy to work around, but thought it would be worth reporting nonetheless.

```php
$configurator->Autolink;
$configurator->BBCodes->addFromRepository('URL');
```

Results in a **Tag 'URL' already exists** error. Similar thing when you do the EMAIL BBCode/Autoemail.

This works fine though:

```php
$configurator->BBCodes->addFromRepository('URL');
$configurator->Autolink;
```

**Comment by s9e** [comment]
It's not a bug, it's a feature! The Autolink/Autoemail need a URL/EMAIL tag. If one already exists, they use that one, otherwise they create one. Then when you try to create a BBCode of the same name, you get the "already exists" error.

You can avoid the error by removing the tags before creating the BBCodes:
```php
unset($configurator->tags['EMAIL']);
unset($configurator->tags['URL']);
```
...or by setting how you want to deal duplicate tags:
```php
$configurator->tags->onDuplicate('error');   // default
$configurator->tags->onDuplicate('ignore');  // ignore the new tag
$configurator->tags->onDuplicate('replace'); // replace the old tag
```

**Comment by tobscure** [comment]
Ah, perfect! You've thought of everything!

**Comment by tobscure** [comment]
Still getting the error when I set `$configurator->tags->onDuplicate('replace')`...
