### ISSUE TITLE
JS parser outputting `<r>` around content, and outputting raw tags

### ISSUE THREAD

**Issue by euantorano** [s9e/TextFormatter#112]
I'm trying to use the JS parser similarly to your demo (and I've also tried using the exact same code form your demo with the same results). The only difference is that I am using the `parse` function rather than `preview`.

The JS `parse()` method seems to be wrapping all of the parsed text in `<r>` and seems to be outputting the raw BBCode tags, with the opening tag wrapped with `<s>`.

____________

It's probably best demonstrated with an example:

**Input**:

```
[b]test[/b]
```

**Output**:

```
<r><B><s>[b]</s>test<e>[/b]</e></B></r>
```

**Expected Output**:

```
<B>test</B>
```

_______________

I have a demo site live here to test: https://euantorano.github.io/mybb_text_editor_demo/public/index.html

The code for this demo site is available here: https://github.com/euantorano/mybb_text_editor_demo

Am I missing something super obvious?

**Comment by JoshyPHP** [comment]
`parse()` returns the same thing as the PHP parser's `parse()`, it's the [XML representation](https://s9etextformatter.readthedocs.io/Getting_started/How_it_works/) of the original text. The JavaScript code does not have a `render()` function because it's more complicated than its PHP counterpart and not very useful. It has a `preview()` function that rolls `parse()` and `render()` into one. If you want to implement a live preview, call `preview()` with the original text and the target HTML element.

https://s9etextformatter.readthedocs.io/JavaScript/Introduction/#api
