### ISSUE TITLE
Not supporting BBC News .co.uk

### ISSUE THREAD

**Issue by thecaretaker1** [s9e/TextFormatter#117]
I'm using the Media Embedded Plugin on phpBB and it will parse:
https://www.bbc.com/news/video_and_audio/must_see/48125671

But I run a UK based forum and it will not recognise:
https://www.bbc.co.uk/news/av/embed/p0783sg7/48125671

which is the embed code from the BBC.co.uk. Can this be added please?

**Comment by JoshyPHP** [comment]
If the bbc.co.uk site works interchangeably with the bbc.com version, I can add support for it, otherwise it should be treated as a separate site.

I don't normally support URLs that are solely used to embed content because that's not what users share but as long as it doesn't cause unexpected issues I'll add it.

Those changes will be part of the upcoming 2.0.0 release, which means it will take a while before the changes trickle down to the default phpBB installation.
