### ISSUE TITLE
No whitespace check for emoticons

### ISSUE THREAD

**Issue by tobscure** [s9e/TextFormatter#12]
If I set up an emoticon for `:/`, then it's replaced into URLs, like:

`http😕/example.org`

I think emoticons should only be replaced if they have whitespace on either side.

**Comment by s9e** [comment]
The short of it is [you can already do something like that](http://s9etextformatter.readthedocs.org/Plugins/Emoticons/Change_regexp/) but it may not be what you want.

In my experience, there are only really two emoticons that sometimes appear in regular text: `8)` and `:/`. There are some irregulars such as `D:` but they're rare. From what I've seen, emoticons in general are moving toward a standardization in the form `:short_name:`, and those don't really have false positives. That's why the default setting is to replace emoticons regardless of their surroundings.

Back to your suggestion, you can't require whitespace around emoticons for several reasons. The first is that they wouldn't be replaced at the beginning or the end of a post. Often times, I've seen that issue resolved by adding a space before and after a text before parsing, then remove it afterwards. It doesn't really work because when such a post is quoted, the quote doesn't start or end with a space and the emoticon isn't replaced. Emoticons are sometimes used in parentheses too, e.g.

 > \*bawdy double entendre\* *(if you know what I mean :wink:)*

There's also the situation when a user adds a row of emoticons without spaces, e.g. :wink::wink::wink:.

Unfortunately, there's no silver bullet. In your case, if you want to use `:/` as an emoticon I'd recommend setting `notBefore` and/or `notAfter` to `\w`.

**Comment by tobscure** [comment]
Fantastic, thanks for the explanation.

**Comment by brunoais** [comment]
Requiring whitespace doesn't mean that it must require that a character exists before and after (see how SCE does it). You may just so a:
If there's a character before, it must be space and if there's a character after, it must be space.
Anyway, those notBefore and notAfter should do the trick.
