### ISSUE TITLE
How to add CSS class to paragraph tag?

### ISSUE THREAD

**Issue by AlfredoRamos** [s9e/TextFormatter#120]
Hi,

I'm developing a Markdown extension for phpBB (3.2.7, TextFormatter 1.4.2) in which I'm using the Litedown and PipeTables plugins and I would like to add a class name to the `<p>` tag.

I can add a custom CSS class to other elements like `table` or headings without problem with the `$configurator` but `P` is not in the `$tags` list in the Litedown plugin and I don't know how to modify the template specified in [`ManageParagraphs`](https://github.com/s9e/TextFormatter/blob/1.4.2/src/Configurator/RulesGenerators/ManageParagraphs.php)

So my question is, how this can be done? Is adding the class with DOM after it has been converted to HTML the only option?

**Comment by JoshyPHP** [comment]
There's no mechanism to change the way paragraphs are displayed. Paragraphs and line breaks are the two things that cannot be changed; They are always displayed as `<p>` and `<br>`.

You're correct, the only way to do that would be to alter the HTML, possibly via DOM manipulation. Alternatively you can get away with using string manipulation instead, since the markup for paragraphs is static. If possible, I'd recommend not changing the markup at all and adjust the CSS selectors to target those paragraphs, e.g. `.myContainer p` instead of `p.myClass`

**Comment by AlfredoRamos** [comment]
I see.

I guess I'll keep the current CSS reset workaround for paragraphs.

Thanks for the response.
