### ISSUE TITLE
Change highlight.js theme

### ISSUE THREAD

**Issue by tobyzerner** [s9e/TextFormatter#121]
What would be the best way to change (or disable) the highlight.js theme? As far as I can see, loading the default theme stylesheet is hardcoded into the `CODE` tag in the BBCode repository.

**Comment by JoshyPHP** [comment]
At the moment, the only way would be to change the template with a simple `preg_replace()`.

I haven't updated the BBCode definition in a while; I'm going to look into it and add a couple of variables so the CDN's URL and the default theme can be set. Afterwards, it'll be possible to use it like this:
```php
$configurator->BBCodes->addFromRepository('CODE', 'default', [
	'theme' => 'github-gist'
	'url'   => 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/'
]);
```

**Comment by tobyzerner** [comment]
Great thanks @JoshyPHP! Will it be possible to disable loading a CDN stylesheet altogether so I can just include a custom one in my app's stylesheet?

**Comment by JoshyPHP** [comment]
I don't know yet but I'll keep that in mind when I update the BBCode's JavaScript.

**Comment by JoshyPHP** [comment]
Quick heads-up about where I stand at the moment.

In the short term, I intend to update the BBCode to allow configuration [as described above](https://github.com/s9e/TextFormatter/issues/121#issuecomment-515743957). If the style name is set to "none", it will not load a stylesheet at all.

In the long term, I intend to remove the inline script from this BBCode and replace it with a new implementation that lives in its own GitHub repository. The BBCode's script does two things: dynamically load highlight.js from its CDN and implement a cache used in live preview. In parallel, I also have a similar script in [this phpBB extension](https://github.com/s9e/phpbb-ext-highlighter/blob/master/s9e/highlighter/styles/all/template/init.js) that dynamically loads highlight.js from its CDN, dynamically loads extra languages for highlight.js but does *not* implement a cache. I'm going to replace both with this new standalone script. Configuration would be done via `data-` attributes on the `script` element, which would be configurable via the BBCode. It would look like this:

```html
<script async src="//cdn.jsdelivr.net/gh/s9e/hljs-loader@1.0.0/dist/loader.min.js"
	data-hljs-style="github-gist"
	data-hljs-url="/path/to/my/hljs/dir/"
	integrity="..."></script>
```

At the same time, I'm reevaluating the use of a cache for live preview. The current cache is a naive implementation; It stores HTML and empties itself every time it's full. A better implementation would use a simple cache eviction strategy, and may even store the highlighted block as a DOM rather than serialized HTML as the latter takes time to reparse at every iteration. On the other hand, a better live preview implementation would make this better cache redundant and any time spent developing it, wasted.

**Comment by tobyzerner** [comment]
Sounds good. Thanks for your amazing and reliable work @JoshyPHP!

**Comment by JoshyPHP** [comment]
Following up on my previous comment, I have published [hljs-loader](https://github.com/s9e/hljs-loader). It automatically loads highlight.js and highlights code blocks on load. Extra languages are automatically loaded as needed, so if somebody uses `[code=rust]` the rust language file will be loaded.

The default `[code]` BBCode will be updated in 2.2 to use hljs-loader. Also in 2.2, two new live preview attributes [data-s9e-livepreview-onupdate](https://s9etextformatter.readthedocs.io/JavaScript/Live_preview_attributes/#data-s9e-livepreview-onupdate) and [data-s9e-livepreview-hash](https://s9etextformatter.readthedocs.io/JavaScript/Live_preview_attributes/#data-s9e-livepreview-hash) are used to better handle deep DOM trees and resource-intensive post-processing such as syntax highlighting. You can try the online demo [here](https://s9e.github.io/TextFormatter/demo.html). Browsers have become particularly efficient at DOM diffing and partial updates so on average the new improved syntax highlighting is barely faster than the old one but it gets much better on pathologically slow cases with big (> 1000 lines) or numerous (> 10) code blocks.
