### ISSUE TITLE
Bug found on formatter, while testing Flarum

### ISSUE THREAD

**Issue by Fastidious** [s9e/TextFormatter#13]
It is under a [Flarum ticket](https://github.com/flarum/core/issues/216#issue-99285561).

**Comment by s9e** [comment]
It may seem counter-intuitive but that's how it works in the original Markdown. You can see how different implementations handle heterogeneous (the first two examples) and partially tight (the third example) lists via Babelmark:

 * http://johnmacfarlane.net/babelmark2/?normalize=1&text=1.+One.%0A2.+Two.%0A*+One.%0A*+Two.
 * http://johnmacfarlane.net/babelmark2/?normalize=1&text=+*+foo%0A+%2B+bar
 * http://johnmacfarlane.net/babelmark2/?normalize=1&text=1.+One.%0A2.+Two.%0A%0A*+One.%0A*+Two.

Any change comes at a cost, and in this case it would be both in development time and in code complexity. Is there a practical use for heterogeneous lists? I try to keep the Litedown plugin lean and focused on real-world usage. I hope that makes sense.

**Comment by franzliedke** [comment]
Well, it wouldn't be CommonMark-compliant, assuming that's where we want to go. :)

The [spec](http://spec.commonmark.org/0.21/#lists) states:
> Changing the bullet or ordered list delimiter starts a new list

I'd argue the same should apply for changing the list type.

**Comment by tobscure** [comment]
CommonMark compliance would be nice, but @s9e does have a point about leanness/complexity. If following CommonMark would bulk up the filesize a huge amount, I'm not sure I would support it.

**Comment by franzliedke** [comment]
Would it? The CommonMark spec is focused on consistency; it mostly defines how to handle edge cases correctly. Apart from that, it isn't much different from other dialects, I think.

**Comment by tobscure** [comment]
I'm basing my concern on how big the reference JS implementation is: [99 kB minified](https://github.com/jgm/commonmark.js/blob/master/dist/commonmark.min.js)

**Comment by s9e** [comment]
@franzliedke If you want full compatibility with Commonmark you'd need a different plugin. This plugin (Litedown) is focused on the most commonly used markup to find the sweet spot between functionality, code complexity and speed.

To achieve a greater degree of compatibility with Commonmark, it would be possible to create a new plugin. Rather than write a Commonmark parser from scratch *(the Commonspark specs stand at 24,478 words at the time of this writing)* I believe it would possible to write a plugin that uses thephpleague/commonmark as a backend. Last time I checked, their AST didn't store the position of markup inside the original text (which is a prerequesite for s9e\TextFormatter) but that shouldn't be too hard to add. At least that's my assumption. On the JavaScript side, maybe it's possible to use jgm/commonmark.js but I don't know enough about it to be certain.

Obviously, there's a cost to it. Beside the time spent implementing it, it would add a dependency to thephpleague/commonmark, it would be a slower and as @tobscure pointed out, jgm/commonmark.js would add a cool 100KB to the live preview.

In my opinion, there's not much value in trying to normalize the result of every edge case. At least not for a forum software. I see how publishing software would want to be compatible with one another, but I don't think edge cases affect forum users all that much as long as they can use the markup they're used to.

My best advice would be to keep Litedown as your default plugin/Markdown flavour and reassess if users complain about a missing feature or if they keep getting tripped by unexpected behaviour.
