### ISSUE TITLE
Ability to convert content between plugins?

### ISSUE THREAD

**Issue by luceos** [s9e/TextFormatter#137]
Is there any possibility for textformatter to parse a saved xml string originally written in markdown to bbcode?

Eg if one would have the litedown type quote `> something` that I could parse it to the bbcode equivalent `[blockquote]something[/blockquote]`.

Thanks!

**Comment by JoshyPHP** [comment]
There's nothing to convert one markup into another. At some point in the future I might provide some API to manipulate markup after parsing but nothing concrete at the moment. I don't think I will ever publish a generic solution for converting a document from markup language to another.

Feel free to tag me if you start anything yourself so I can give it a look. Otherwise, you may look into Pandoc (not in PHP), I remember that Friendica has something they use internally but it's probably limited to the markup they support, and I think The League of Extraordinary Packages has a package that converts Markdown to and/or from BBCodes but I don't remember the specifics.

**Comment by luceos** [comment]
Okay thanks Joshy. The league has a HTML to Markdown converter. It's not likely I will create something to add this functionality, my best bet right now is to temporarily run the specific flarum install with bbcode and switch to an easier editor (wysiwyg or alternatives) in the future.
