### ISSUE TITLE
Custom BBCode encodes HTML output

### ISSUE THREAD

**Issue by davemacaulay** [s9e/TextFormatter#139]
Hey there! Firstly I want to say thank you for the amazing library, a huge improvement over the outdated BBCode library I was using previously. I've been scouring the docs and reading the source code for the best part of a few hours and I'm unable to determine how to do the following.

I have custom BBCodes in my solution which require PHP to be executed and then return. For instance [player=16][/player] should use the name renderer to render the username and return it.

I've configured my custom rule as follow:
```
$configurator->BBCodes->bbcodeMonkey->allowedFilters[] = 'bbcode::SGetFormattedUserName';
$configurator->BBCodes->addCustom(
    '[player={TEXT;useContent;postFilter=bbcode::SGetFormattedUserName}]{TEXT}[/player]',
    '{TEXT}'
);
```

The response of `bbcode::SGetFormattedUserName` is a HTML string.

However this results in the output being a string rather than parsing it as HTML:
![image](https://user-images.githubusercontent.com/1774374/77255691-5d261780-6c37-11ea-9cb6-94e754c32577.png)

I'll continue to dig and see if I can resolve this on my own but I'd really appreciate any pointers / help

**Comment by JoshyPHP** [comment]
Attribute filters are meant to validate and possibly fix/normalize/sanitize user input but they are not meant to be used for presentation. The value from an attribute filter is treated the same way as user input, which means it's escaped by default.

If you want to generate some custom HTML based on user input using your own logic or template engine, the best solution would be to post-process the HTML generated by the library. For example:

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addCustom(
	'[player id={UINT}]',
	'<a data-player-id="{UINT}"></a>'
);

extract($configurator->finalize());

$text = '[player=16][/player]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

$html = preg_replace_callback(
	'(<a data-player-id="(\\d++)"></a>)',
	function ($m)
	{
		$id = (int) $m[1];

		return '<a href="viewprofile.php?id=' . $id . '">...</a>';
	},
	$html
);

die("$html\n");
```
```html
<a href="viewprofile.php?id=16">...</a>
```

In this example, I used a simple template for the `[player]` BBCode that's easy to match and replace in PHP. In addition, I used a `{UINT}` token for the player's ID since it looks like an unsigned integer. I gave a name, `id` to the attribute because it's a good practice. The first attribute declared is set as the default attribute, which means you can use `[player id=16]` or `[player=16]` indifferently. You don't have to use `useContent` in the definition unless you want users to be able to enter `[player]16[/player]`.

Let me know if you have any other questions.

**Comment by davemacaulay** [comment]
Ah okay, thanks for the explanation & providing a solution, it makes sense for the BBCode engine to escape output.

Looks like it'll work, thanks for your quick response :)
