### ISSUE TITLE
Markdown header crashes JavaScript preview

### ISSUE THREAD

**Issue by tobscure** [s9e/TextFormatter#14]
http://s9e.github.io/TextFormatter/fatdown.html

Clear the text box, then type #, a space, and then a letter. It freezes the Chrome/Safari, not sure about other browsers.

Originally from flarum/core#215

**Comment by s9e** [comment]
Awesome, thanks for the heads-up. It was an infinite loop cause by a faulty assumption on my part. Specifically, that the regexp `#+[ \t]*(?=.)` would match any number of pound signs followed by any amount of whitespace followed by something else and that "something else" would be some actual text. In actuality, if there's no text the regular expression engine can backtrack to satisfy `(?=.)` with the space. I could have replaced the expression with a possessive quantifier `#+[ \t]*+(?=.)` but possessive quantifiers are not supported in JavaScript. Instead, I replaced it with `#+[ \t]+(?=\S)`.

Weirdly enough, a number of Markdown implementations do not require any text in headers. I wonder if it's intentional.

 * http://johnmacfarlane.net/babelmark2/?normalize=1&text=%23
 * http://johnmacfarlane.net/babelmark2/?normalize=1&text=%23%20

**Comment by brunoais** [comment]
You can simulate possessiveness in javascript. If you want me to show you, just ask.
