### ISSUE TITLE
phpbb and default img bbcode compatibility

### ISSUE THREAD

**Issue by luceos** [s9e/TextFormatter#145]
Hi @JoshyPHP,

I've been working on a migration where a larger (100+ million posts) phpbb instance is kept in sync with @flarum. In order to do this I have created a compatibility layer where both content types can be parsed to another. One issue I am having is that Flarum uses the default `[img width=N height=Y]` format and phpbb uses [img=NxY:hash]`. The hash isn't an issue, it is stripped out. But how do I allow both formats to co-exist in one declaration?

I tried editing the bbcode repository, but I have no idea how to assign the N and Y to the width and height variables used internally.

```
	<bbcode name="IMG">
		<usage>[IMG src={URL;useContent} title={TEXT?} alt={TEXT?} height={UINT?}  width={UINT?} ]</usage>
		<template><![CDATA[
			<img src="{@src}" title="{@title}" alt="{@alt}">
				<xsl:copy-of select="@height"/>
				<xsl:copy-of select="@width"/>
			</img>
		]]></template>
	</bbcode>
```

**Comment by rxu** [comment]
Just for a note, default phpBB `[img]` tag has no dimension parameters at all.

**Comment by luceos** [comment]
@rxu that might be true, I have no idea to what extend modifications have been added.

**Comment by JoshyPHP** [comment]
The cute way is to use this for the definition:
```
[IMG={UINT1}x{UINT2} src={URL;useContent} title={TEXT?} alt={TEXT?} height={UINT1?}  width={UINT2?}]
```
Internally it will be interpreted as this:
```
[IMG img={PARSE=/^(?<width>0|[1-9]\d*)x(?<height>0|[1-9]\d*)$/D} src={URL;useContent} title={TEXT?} alt={TEXT?} height={UINT1?}  width={UINT2?}]
```
When the BBCode is parsed its default value is stored in an `img` attribute, then it's parsed and other attribute values are extracted from it. (see [attribute preprocessors](https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Custom_BBCode_syntax/#attribute-preprocessors)) Because we don't formally define an `img` attribute, it's not stored in the XML.

Note however, that it changes the default attribute for that BBCode. In your definition, `src` is the default attribute, which means the BBCode can be used as `[img=pic.png]`. In the definition above, that wouldn't work. You can keep `src` as the default attribute by declaring the attribute preprocessor later in the definition, e.g.
```
[IMG src={URL;useContent} title={TEXT?} alt={TEXT?} height={UINT?}  width={UINT?}
	src={PARSE=/^(?<width>\d+)x(?<height>\d+)$/D}
]
```
In that case, though, if you use `[img=12x34]pic.png[/img]` you'll end up with `12x34` as the value for `src`. If that's an issue, you can keep `img` as the default attribute and set up different attribute preprocessors to assign the default value to the right attributes depending on whether it looks like dimensions or not.
```
[IMG
	img={PARSE=/^(?<width>\d+)x(?<height>\d+)$/D}
	img={PARSE=/^(?!\d+x\d+)(?<src>.*)/D}
	src={URL;useContent} title={TEXT?} alt={TEXT?} height={UINT?}  width={UINT?}
]
```

Full code below for easy reproducibility:
```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addCustom(
alt={TEXT?} height={UINT1?}  width={UINT2?}]',
	'[IMG
		img={PARSE=/^(?<width>\\d+)x(?<height>\\d+)$/D}
		img={PARSE=/^(?!\\d+x\\d+)(?<src>.*)/D}
		src={URL;useContent} title={TEXT?} alt={TEXT?} height={UINT?}  width={UINT?}
	]',
	'<img src="{@src}" title="{@title}" alt="{@alt}">
		<xsl:copy-of select="@height"/>
		<xsl:copy-of select="@width"/>
	</img>'
);

extract($configurator->finalize());

$text = "[img]pic.png[/img]\n"
      . "[img=pic.png /]\n"
      . "[img src=12x34 /]\n"
      . '[img=12x34]pic.png[/img]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<img src="pic.png" title="" alt="">
<img src="pic.png" title="" alt="">
<img src="12x34" title="" alt="">
<img src="pic.png" title="" alt="" height="34" width="12">
```

**Comment by luceos** [comment]
You are so awesome @JoshyPHP; thanks for this I will most certainly try this out!

**Comment by JoshyPHP** [comment]
For completeness and in case it's easier than editing the original BBCode definition, you can use the regular API to apply the changes after the BBCode was created.:
```php
// Change the name of the default attribute to something that is not defined.
// The value won't be stored in the XML
$attrName = 'whatever';
$configurator->BBCodes['IMG']->defaultAttribute = $attrName;

// Add the attribute preprocessors using the temporary attribute as source
$tag = $configurator->tags['IMG'];
$tag->attributePreprocessors->add($attrName, '/^(?<width>\\d+)x(?<height>\\d+)$/D');
$tag->attributePreprocessors->add($attrName, '/^(?!\\d+x\\d+$)(?<src>.*)/D');
```
