### ISSUE TITLE
Mailru and audiomack does not work

### ISSUE THREAD

**Issue by ayyilmaz** [s9e/TextFormatter#147]
And example links from the mailru and audiomack sources don't work.
 https://github.com/s9e/TextFormatter/blob/master/src/Plugins/MediaEmbed/Configurator/sites/mailru.xml 

https://github.com/s9e/TextFormatter/blob/master/src/Plugins/MediaEmbed/Configurator/sites/audiomack.xml

**Comment by JoshyPHP** [comment]
They work for me.

**Comment by ayyilmaz** [comment]
> They work for me.

I tries on flarum that use s9e/TextFormatter . Yes Mailru is working but it does not work some mailru video urls include **toplclips** "https://my.mail.ru/v/topclips/video

Audiomack does not work for me I tested this url: https://audiomack.com/santi-333/song/birak-beni-haykirayim

**Comment by JoshyPHP** [comment]
I don't have an up-to-date Flarum installation and I can only test that kind of things on their own.

That Mail.ru page cannot be embedded, only individual videos can.

Audiomack seems to have changed the format of their URLs, that's why this one is not supported. I'll see if I can add support for it. In the meantime you can probably use https://audiomack.com/song/santi-333/birak-beni-haykirayim instead.
