### ISSUE TITLE
HLJS Loader Error

### ISSUE THREAD

**Issue by tankerkiller125** [s9e/TextFormatter#153]
I just recently noticed that the code highlighting is failing and upon investigation I found that the CDN url isn't loading and is instead giving a 404 error. 

![image](https://user-images.githubusercontent.com/3457368/95745739-9a013c80-0c63-11eb-8952-60c097df9d37.png)

**Comment by JoshyPHP** [comment]
Thanks for the heads-up. I must have forgotten to tag the 1.0.14 release, that's fixed now.

**Comment by JoshyPHP** [comment]
It seems that jsDelivr has the wrong file cached for the moment but it should fix itself within an hour when their cache expires. I'll close this issue after confirming it.

**Comment by tankerkiller125** [comment]
It looks like it's on the CDN now, now just the integrity issue based on looking at things myself.

Thanks for the quick response! Your library is truly awesome!

**Comment by JoshyPHP** [comment]
Yes, the file is on jsDelivr's CDN but there must have been a bit of a race condition in their caching system and instead of getting the correct `loader.min.js` file from the repository, it took the `loader.js` file from the repo, minified it and cached that instead. That's why the integrity check fails at the time of this writing.

It's possible to slightly change the URL to access a fresh copy of the correct file, if that's any use. For example, by changing the tag's template:
```php
$tag = $configurator->tags['CODE'];
$tag->template = str_replace('/loader', '//loader', $tag->template);
```

You end up loading a different URL that points to the correct copy:

 - https://cdn.jsdelivr.net/gh/s9e/hljs-loader@1.0.14/loader.min.js
 - https://cdn.jsdelivr.net/gh/s9e/hljs-loader@1.0.14//loader.min.js
