### ISSUE TITLE
[MediaEmbed] anchor.fm iframe is broken

### ISSUE THREAD

**Issue by iPurpl3x** [s9e/TextFormatter#158]
I noticed that there is a strange thing happening with the [anchor.fm](https://anchor.fm) embed generated by the MediaEmbed plugin. Basically there is an element in the iframe that overlays half of the main element and makes it impossible to interact with it.

To be sure that this was not related to my environment, I cloned this repo and generated a "MediaEmbed Test Page" with  `srcipts/generateMediaEmbedTestPage.php anchor`

The result is not looking good:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/18526076/107510125-d1e1a780-6ba3-11eb-955b-c4175768b62d.png">

As a hint for fixing this, I saw that when you generate an iframe code from [anchor.fm](https://anchor.fm) it the `src` part looks different than the one generated by TextFormatter.

**Comment by JoshyPHP** [comment]
As far as I can tell, that's an issue in Anchor's layout. What happens when you post the same podcast twice in succession?

**Comment by iPurpl3x** [comment]
@JoshyPHP 
> What happens when you post the same podcast twice in succession?

You mean that ? Still the same issue.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/18526076/107539669-7aecca00-6bc5-11eb-9e10-6929d49ebd42.png">

**Comment by JoshyPHP** [comment]
The green thing is an overlay that should be right outside the viewport and I suspect should slide in from the top. On Firefox 85.0.1, when displaying multiple consecutive embeds the first one would have the green thing but the others would not. After upgrading Firefox all of them have the green thing, which is quite remarkable. I can't test it on Chome/Chromium because the embed freezes its document for some reason.

If I reduce the width of the embed, the green overlay is less visible but it still obscures the podcast's title. There's a logic that determines whether the overlay is shown but I can't quite figure it out. It seems that adding a component to the embed URL is enough to make it go away and it also fixes the issue with Chrom(e|ium) so I'm going to tweak the URL of the embed page accordingly.

The default URL suggested by Anchor contains the podcast's name and the episode's title but those do not appear to make a meaningful difference and can be replaced with any placeholder (just `x` in current code.) That's good because if the URL required them, they would have to be scraped and it would make embedding more complicated. Also, Anchor's default embed is fixed to 400px wide but that doesn't seem to make a difference either so I'll leave it to a fluid width, limited to 768px because higher values trigger a change in layout.

**Comment by iPurpl3x** [comment]
Thank you @JoshyPHP for the quick fix. I deployed it for my client and it is all fine now ! (see [example](https://community.upc.ch/d/14375-s02e01-der-beginn-einer-neuen-ara-serhat-koroglu))
