### ISSUE TITLE
False gist rendering attempt

### ISSUE THREAD

**Issue by johnd0e** [s9e/TextFormatter#171]
For [this gist](https://gist.github.com/rohitmanhas02/154fb86ff8c9bdd9dea743d0afee9bc8) the download link is https://gist.github.com/rohitmanhas02/154fb86ff8c9bdd9dea743d0afee9bc8/archive/229e79aaa5699f0010b790f61a5164c038789d16.zip

If I type that in a post on phpbb board it is not rendered as text. Instead I see pretty large empty space.
![image](https://user-images.githubusercontent.com/1838643/128595851-5967164f-534a-4321-93bf-81faaad86b19.png)

**Comment by JoshyPHP** [comment]
That Gist does not exist, so GitHub doesn't have anything to display for it. The best I can do is leave an error message to somewhat hint that it's missing.

**Comment by johnd0e** [comment]
> That Gist does not exist

That gist was existing on the moment of writing.
But that does not matter as you xcan reproduce it with any other, e.g. https://gist.github.com/Untrusted-Game/172a510a34cf0ba9cf7533dc9f55d960/archive/ffe65e387a97ee479cbeaa82660f5af42aa80cb1.zip

**Comment by JoshyPHP** [comment]
That URL isn't transformed into anything, it remains as-is. Is that your issue?

**Comment by JoshyPHP** [comment]
AFAICT, that URL differs from the list of supported URLs in two ways; The first is the username contains a dash, which is currently not recognized. That'll be fixed in the next release. The other is that it's an archive link, which means the path contains the string `archive/` in the middle of what's used as an ID. That's not currently supported and there's no simple way to support those because there's no built-in filter to perform string replacements. It is possible to scrape the page to get a permalink but I don't know whether that's worth it, considering links to archives are probably meant to be used to download the file rather than embed its content. Is there a reason you or your users publish archive links rather than the "Share" link that appears on the Gist's page?

**Comment by johnd0e** [comment]
> It is possible to scrape the page to get a permalink but I don't know whether that's worth it,

Definitely not worth - I'd prefer leave such url as plain links, without embedding content.


> Is there a reason you or your users publish archive links rather than the "Share" link

The reason is simple - this direct link meant to be used to download archive without visiting github.
