### ISSUE TITLE
Line break with PipeTables

### ISSUE THREAD

**Issue by iamdarkle** [s9e/TextFormatter#179]
I don't know if this feature exists in this package, but it is possible to make a line break in the same cell, maybe it is not [documented](https://s9etextformatter.readthedocs.io/Plugins/PipeTables/Syntax/)?

I mean this for example here on Github:

| Fruit         | Price                   | Advantages              |
| ------------- | ----------------------- | ----------------------- |
| Bananas       | first line<br>next line | first line<br>next line |
| Bananas       | first line<br>next line | first line<br>next line |

**Comment by JoshyPHP** [comment]
No, each line in the original text creates a new row. You can create line `<br>` elements through other markup such as BBCodes, but that's it.

**Comment by JoshyPHP** [comment]
I should also note that it would be complicated to support due to the core design of the library and its storage format. The library preserves the original input in its XML and treats it as a 1-dimensional stream of characters, whereas this kind of markup requires the input to be handled as a 2-dimensional grid. For example, consider this 4-cells table:
```
a|b
a|b
-+-
c|d
c|d
```
The order of the data in the input it `ababcdcd`, but the output should be `aabbccdd`. This would have to be reordered at rendering time. I'm going to post a snippet below that illustrates how it can be done for safekeeping and possible future reference.

```php
$xml = new DOMDocument;
$xml->loadXML('<r><TABLE><TR><TD col="0" row="0"/><TD col="1" row="0"/></TR><TR><TD col="0" row="1"/><TD col="1" row="1"/></TR><CELL col="0" row="0">a</CELL>|<CELL col="1" row="0">b</CELL>
<CELL col="0" row="0">a</CELL>|<CELL col="1" row="0">b</CELL>
-+-
<CELL col="0" row="1">c</CELL>|<CELL col="1" row="1">d</CELL>
<CELL col="0" row="1">c</CELL>|<CELL col="1" row="1">d</CELL>
</TABLE></r>');

$xsl = new DOMDocument;
$xsl->loadXML('<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" encoding="utf-8" />
	<xsl:template match="TABLE">
		<table><xsl:apply-templates select="TR"/></table>
	</xsl:template>
	<xsl:template match="TR">
		<tr><xsl:apply-templates select="TD"/></tr>
	</xsl:template>
	<xsl:template match="TD">
		<td><xsl:apply-templates select="../../CELL[@col = current()/@col][@row = current()/@row]"/></td>
	</xsl:template>
</xsl:stylesheet>');

$xslt = new XSLTProcessor;
$xslt->importStylesheet($xsl);

echo $xslt->transformToXml($xml);
```

**Comment by iamdarkle** [comment]
Thank you very much for the information, considering the complication involved because of the core design you have explained to me, the BBcode idea in the short term doesn't sound bad, I leave it to your choice if you want to close the issue or leave it for future research on this 🙂

**Comment by JoshyPHP** [comment]
I'm closing it for now because I don't have any plans for extending the table markup in the foreseeable future.
