### ISSUE TITLE
💡Improving front end performance of MediaPack

### ISSUE THREAD

**Issue by nomind60s** [s9e/TextFormatter#189]
I noticed that page load speeds between forum posts with embedded content (i.e. MediaPack sites) seems slower than other media sites. This seems particularly obvious with tweets (Twitter.com) that are commonly found embedded in various places. Digging a bit deeper, and viewing page source revealed things like:

```
<link rel="preconnect" href="https://example.com">
<link rel="dns-prefetch" href="//example.com">
```
where example.com is replaced by some twitter.com references when embedded tweets are involved.  

Dr. Google lead me to [Prefetching, preloading, prebrowsing \| CSS\-Tricks \- CSS\-Tricks](https://css-tricks.com/prefetching-preloading-prebrowsing/) and others. 

Could the page load speeds for forum posts with embedded media benefit from something like this?

**Comment by JoshyPHP** [comment]
No, it would benefit from the opposite; Rather than prefetching, the way to improve the performance of embed-heavy pages is lazy loading. By default, the library enables [native browser lazy loading](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading) but its performance depends on the browser's implementation itself. My preference goes to lazy loading iframes in userland but the way to implement it depends on the user interface.

**Comment by nomind60s** [comment]
Thanks for the reply. Just thinking out load. Ok to close this.
