### ISSUE TITLE
Forced Full-screen Embedding of Facebook Videos on Mobile Devices -

### ISSUE THREAD

**Issue by efast1568** [s9e/TextFormatter#220]
when clicking to play a  Facebook video, it is forced to  fullscreen mode on mobile devices. Is there a way to adjust the formatting settings to resolve this issue? 

https://waterhole.subarist.net/posts/94853-mediaembed-test/comments/573919

BR & Thank u

**Comment by JoshyPHP** [comment]
Not really, no. Apparently, Facebook manually sets the video to play in full screen on mobile. Maybe it's possible to completely prevent the video from playing in full screen but it would prevent intentional use as well. Either way, that's a design choice from Facebook and they don't offer a way to change it.
