### ISSUE TITLE
BBCode regexp stopped working (phpBB)

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#222]
Is there probably some known library change that would make this construction to stop working (phpBB 3.3.2 & Textformatter 2.7.5 vs phpBB 3.3.10 & Textformatter 2.11.5):

BBCode:
`[css]{REGEXP=/^[\-\.,;:' #\{\}0-9a-zA-Z]+$/}[/css]`
HTML replacement:
`<style type="text/css">{REGEXP}</style>`

I'd  think it's phpBB issue but couldn't find any related changes in the core so far.
Thanks.

**Comment by JoshyPHP** [comment]
This one is not immediately obvious so it took me a hot minute to figure out. By default, rules are automatically generated to [enforce the HTML content model](https://s9etextformatter.readthedocs.io/Rules/Rules_generators/#enforcecontentmodels) so nesting BBCodes in a certain way would not break the layout. At the root of a document, the library enforces the `div` element's content model (it allows pretty much anything but meta elements) and since `style` isn't allowed in `div`, it is ignored. The library actually goes one step further by figuring out that this BBCode cannot be used anywhere in a text and removes it altogether, but that doesn't matter here.

What you need to do is specifically allow this BBCode at the root of the text, or allow it on a per-BBCode basis.

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addCustom(
	'[css]{REGEXP=/^[\-\.,;:' #\{\}0-9a-zA-Z]+$/}[/css]',
	new s9e\TextFormatter\Configurator\Items\UnsafeTemplate('<style type="text/css">{REGEXP}</style>')
);

$configurator->rootRules->allowChild('CSS');

extract($configurator->finalize());

$text = '[css]font-size: 3px;[/css]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<style type="text/css">font-size: 3px;</style>
```

**Comment by rxu** [comment]
Ah, so in phpBB context that requires an extension.
Thanks for the explanation.

**Comment by JoshyPHP** [comment]
Yeah, you can only set the root context in PHP. In theory, you could create a BBCode that creates a new context and manually allow another BBCodes that is used to create the `style` element. The parent BBCode can automatically create the child tag and perform validation, the child tag would not be able to perform validation and should only be used inside of the parent. That's a big hack IMO, and I don't recommend using that kind of constructs.

```php
$configurator = new s9e\TextFormatter\Configurator;

$configurator->BBCodes->addCustom(
	"[css #allowChild=STYLE #createChild=STYLE #isTransparent=false]{REGEXP=/^[\-\.,;:' #\{\}0-9a-zA-Z]+$/}[/css]",
	'<xsl:apply-templates/>'
);
$configurator->BBCodes->addCustom(
	"[style #requireParent=CSS]{TEXT}[/style]",
	new s9e\TextFormatter\Configurator\Items\UnsafeTemplate('<style type="text/css"><xsl:apply-templates/></style>')
);

extract($configurator->finalize());

$text = '[css]display:none[/css]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<style type="text/css">display:none</style>
```
