### ISSUE TITLE
YouTube embed regression on commercial videos

### ISSUE THREAD

**Issue by PrimateCoder** [s9e/TextFormatter#235]
Recently, commercial YouTube videos have been failing to embed on [🎹 Piano | Tell](https://forum.pianotell.com).

Here is an example video that fails to embed:
https://youtu.be/muxgwcxW-zo

This fix addresses it but the tests need updating. Note that the embed code generated by YouTube includes this attribute as well. I believe this is OK as a general default, but it wouldn't take much to apply it to YouTube only.

```
navindra@flight TextFormatter % git show
commit 777484d449833c14a289e7c19b3d4524f59466de (HEAD -> master)
Author: Navindra Umanee <navindra@flight.local>
Date:   Tue Jul 16 14:59:39 2024 +0400

    Added a referrerpolicy to address YouTube regression for many commercial videos
    
    This seems like a reasonable default to use across the board.

diff --git a/src/Plugins/MediaEmbed/Configurator/TemplateGenerators/Iframe.php b/src/Plugins/MediaEmbed/Configurator/TemplateGenerators/Iframe.php
index 765b4e96f..b56ce4dc9 100644
--- a/src/Plugins/MediaEmbed/Configurator/TemplateGenerators/Iframe.php
+++ b/src/Plugins/MediaEmbed/Configurator/TemplateGenerators/Iframe.php
@@ -18,7 +18,8 @@ class Iframe extends TemplateGenerator
                'allowfullscreen' => '',
                'loading'         => 'lazy',
                'scrolling'       => 'no',
-               'style'           => ['border' => '0']
+               'style'           => ['border' => '0'],
+               'referrerpolicy'  => 'strict-origin-when-cross-origin'
        ];
 
        /**
```

**Comment by JoshyPHP** [comment]
As far as I can tell, that video works just fine with the default settings. Modern versions of both [Google Chrome](https://developer.chrome.com/blog/referrer-policy-new-chrome-default) and [Firefox](https://blog.mozilla.org/security/2021/03/22/firefox-87-trims-http-referrers-by-default-to-protect-user-privacy/#:~:text=Firefox%2087%20new%20default%20Referrer%20Policy) default to `strict-origin-when-cross-origin`. What you're experiencing may be due to a browser setting, or a privacy extension.

I'd rather not override a user's referrer policy unless absolutely necessary, as it may weaken the user's desired privacy level. If someone has configured their browser to *not* send referrers at all, I don't want to force them to.

**Comment by JoshyPHP** [comment]
I forgot to mention that you can always modify a template in user space via an extension. For example, this is how you'd add a `referrerpolicy` to the `YOUTUBE` template:

```php
$dom = $configurator->tags['YOUTUBE']->template->asDOM();
$dom->firstOf('//iframe')->setAttribute('referrerpolicy', 'strict-origin-when-cross-origin');
$dom->saveChanges();
```
