### ISSUE TITLE
Facebook embeds not working if on mobile

### ISSUE THREAD

**Issue by wolnavi** [s9e/TextFormatter#240]
Hi, not sure if this is the right place to seek help so apologies if this is the wrong place..

I am browsing a public forum and I think they are using your plugin. So if i'm on a desktop PC, I am able to view Facebook embeds. However if i'm on mobile or if I try to emulate(?) the browser's view to mobile view via Chrome's DevTools on PC, the said Facebook embed is no longer viewable.. Wondering if you are able to fix it..? I tried to use the [Fatdown demo](https://s9e.github.io/TextFormatter/fatdown.html) and the same issue persists

PC view:
![image](https://github.com/user-attachments/assets/309c9902-a171-4723-b06b-5e347519b174)

Mobile view:
![image](https://github.com/user-attachments/assets/74de2916-5312-42a0-b5af-e73520b6adff)

**Comment by JoshyPHP** [comment]
Hi,

Yes, this is as good a place as any, no worries.

I've just checked Facebook and indeed, the content doesn't load when emulating a mobile browser in Chromium or Firefox. I have confirmed that this is not only the case for [the way this library works specifically](https://s9e.github.io/iframe/2/facebook.min.html#p451016937058647) but also when using [Facebook's official embed code](https://developers.facebook.com/docs/plugins/embedded-posts/). As far as I can tell, Facebook automatically redirect mobile browsers to the `m.facebook.com` domain, which is configured to prevent embedding via an iframe. That's an oversight on their part and only Facebook would be able to fix it. I'm surprised they haven't fixed it already.

So, for now there's nothing we can do about it. You can try contacting Facebook if they have a way to report bugs, otherwise we'll just have to wait for someone working there to notice it.

I'm going to close this issue for now but feel free to reopen if you get more info or if embeds work when using Facebook's official code but not when using this library.

**Comment by wolnavi** [comment]
Alright, I've reported it to them, hopefully they will see
