### ISSUE TITLE
[question] a way to enable all HTML + Unsafe tags

### ISSUE THREAD

**Issue by sijad** [s9e/TextFormatter#36]
I'm looking for a easy way to enable HTML, is there any way to approach this?

**Comment by JoshyPHP** [comment]
No easy way, because almost everything in the library operates as a whitelist. The closest you can get to enable any HTML is to allow every known tag and attribute.

**Comment by sijad** [comment]
that's going to be hard that way, it also make the configure file a lot beigger

**Comment by sijad** [comment]
I need a way to allow users use HTML in https://github.com/sijad/flarum-ext-pages, but knowing all of HTML tags and attributes it's not way to go. in this case maybe it's better to show the unparsed text directly (if page marked as HTML) it will solve the "HTML" problem, on other hand some good stuff like auto links, auto media, etc will be disabled.

thanks for your great afford

**Comment by JoshyPHP** [comment]
It doesn't really matter if it takes a lot of code to configure the parser since that's something that should only be done once and then cached. The parser and renderer objects *will* get bigger with all the extra tags but a lot of the redundancy is optimized away and it shouldn't make any kind of noticeable difference in terms of performance or resource usage.

With that said, since this is an admin-only feature you may not want to touch Flarum's main parser at all. After all, you don't want normal users to have access to unsafe HTML. So you'll probably have to create a secondary set of parser/renderer for those admin pages. Or maybe the simplest solution would be to let the admins edit those pages as HTML directly, maybe with a rich text editor. As you pointed out, the downside is that you lose some of the niceties such as autolinks.

**Comment by sijad** [comment]
> With that said, since this is an admin-only feature you may not want to touch Flarum's main parser at all. After all, you don't want normal users to have access to unsafe HTML. So you'll probably have to create a secondary set of parser/renderer for those admin pages.

already did https://github.com/sijad/flarum-ext-pages/commit/482cf321434221f0d00a2a1b12c2cd9c8af26121

but I'm still not sure if adding all html tags it's good idea, produced `js` will be huge, I probably use another option

**Comment by JoshyPHP** [comment]
For what it's worth, adding all elements/attributes from the current HTML5 specs adds about 25.5 KB to the minified parser, using the latest commit.

Here's what I used to scrape the data from the W3C's specs:
```php
$dom   = new DOMDocument;
@$dom->loadHTMLFile('https://www.w3.org/TR/html5/index.html', LIBXML_COMPACT | LIBXML_NOBLANKS);
$xpath = new DOMXPath($dom);
$tbody = $xpath->query('//h3[@id="elements-1"]/following-sibling::table[1]/tbody')->item(0);
foreach ($tbody->getElementsByTagName('th') as $th)
{
	foreach (preg_split('(\\s*,\\s*)', $th->textContent) as $elName)
	{
		$attributes = $xpath->evaluate('string(./following-sibling::td[5])', $th);
		$attributes = preg_replace('(\\bglobals\\b)', 'accesskey class contenteditable dir hidden id lang spellcheck style tabindex title translate', $attributes);

		$configurator->HTMLElements->allowUnsafeElement($elName);
		foreach (preg_split('(\\W+)', $attributes, -1, PREG_SPLIT_NO_EMPTY) as $attrName)
		{
			$configurator->HTMLElements->allowUnsafeAttribute($elName, $attrName);
		}
	}
}
```

**Comment by sijad** [comment]
`25.5KB` regex in preview will dry mobile butteries, I still think the other option is preferred.

thanks again

**Comment by JoshyPHP** [comment]
There's no 25 KB regexp and even if there was I don't think it would make any difference in terms of power usage, but I agree that you're probably better off using hardcoded HTML directly.
