### ISSUE TITLE
Add feature to sanitize attributes values

### ISSUE THREAD

**Issue by sijad** [s9e/TextFormatter#37]
what currently is missing:

* a way to specifying whitelisted value kind (numerical, alphabetical, numerical + css sizes, etc)
* filter `style` attribute to allow only some css attributes like `color` or `font`
* filter `class` attribute to allow only some specific classes

for first problem `HTMLElements::allowAttribute` can also accept a third argument which can be a string (which can be numerical, alphabetical, ...) or regex (which is useful for some specific usage. like sanitize `src` value).
this argument also could be callable function but I think that not gonna available in front-end then.

with implementing this the two other problem also can be fixed but if `HTMLElements` had some method for whitelisting css styles and classes for specific tags that'd be great.

**Comment by JoshyPHP** [comment]
`allowElement()` and `allowAttribute()` return an object with a `filterChain` property. You can add any number of [built-in filters](http://s9etextformatter.readthedocs.io/Filters/Built-in_filters/) or [custom filters](http://s9etextformatter.readthedocs.io/Filters/Attribute_filters/#add-a-custom-attribute-filter) to validate/sanitize either the element as a whole or the attribute's value.

There's a built-in filter for whitelists of values, `#choice`. It's currently missing from the doc, I'm going to add it.

I don't think I'll add a filter for CSS because it's just too complicated and would deserve to exist as its own project. Maybe use something like HTMLPurifier if their CSS sanitizer can be used separately.

```php
$configurator = new s9e\TextFormatter\Configurator;

$configurator->HTMLElements->allowElement('span');

$attribute = $configurator->HTMLElements->allowUnsafeAttribute('span', 'style');
$attribute->filterChain->append('#regexp')->setRegexp('/^color:\\s*#?\\w+$/');

$attribute = $configurator->HTMLElements->allowAttribute('span', 'class');
$attribute->filterChain->append('#choice')->setValues(['foo', 'bar']);

extract($configurator->finalize());

$text = '<span class="red" style="color:red">..</span>'
      . '<span class="foo" style="display:block">..</span>';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```

**Comment by sijad** [comment]
thanks for answer

**Comment by sijad** [comment]
@JoshyPHP is it possible to allow an attribute to all tags? or I have to add it one by one?

**Comment by JoshyPHP** [comment]
One by one. You can iterate over `$configurator->tags` if that helps.
