### ISSUE TITLE
Imgur album problem?

### ISSUE THREAD

**Issue by terabin** [s9e/TextFormatter#49]
Image:
http://imgur.com/a/2QYHI

Page with the problem:
http://4tabern.com/d/5553-nier-automata-novos-detalhes-do-combate-e-imagens-do-jogo

Actually use this extension:
https://github.com/s9e/flarum-ext-mediaembed

TextFormatter v0.8.1

This don't happens with all images in album.

**Comment by JoshyPHP** [comment]
That's an issue with Imgur, either with the albums or with a server. On Firefox that image is displayed normally. The thumbnail of the one before says it has been removed but it works anyway for some reason. On Chromium, some images don't work because of a 503 server error.

If it's a server error, it's most likely temporary. Either way, there's nothing we can do I'm afraid.

**Comment by terabin** [comment]
After imgur update, the album don't work anymore.

**Comment by JoshyPHP** [comment]
I don't think you're using 0.8.1 because the current markup for Imgur albums is not the one I see on your site. You may need to wait for the next Flarum update.

**Comment by terabin** [comment]
I tested with last version now, I get this error in console:

Uncaught TypeError: _.templates.album.embedStyles is not a function

The images in the album are not loaded

**Comment by JoshyPHP** [comment]
It's an issue in Imgur's JavaScript. There's nothing either of us can do about it.
