### ISSUE TITLE
Custom Plugins

### ISSUE THREAD

**Issue by RikSomers** [s9e/TextFormatter#54]
Hello,

Is it possible to write custom plugins?

As far as I can tell, the Configurator that is shipped with the default installation of TextFormatter has the classname hardcoded to ``$className  = 's9e\\TextFormatter\\Plugins\\' . $pluginName . '\\Configurator';``, which makes it hard to do a custom plugin!

Thanks!

**Comment by JoshyPHP** [comment]
You rarely have to create a custom plugin. If the [Preg plugin](http://s9etextformatter.readthedocs.io/Plugins/Preg/Synopsis/) does not satisfy your needs, you can [plug your own parser](http://s9etextformatter.readthedocs.io/Plugins/Your_own_plugin/Register_parser/) without registering a configurator.

You can create you own complete plugin with the same features as the default ones. I haven't written any docs for it so here's a crash course. You need two classes: a configurator, and a parser. You can set your plugin's configurator as a property of the main configurator. Its name must start with an uppercase letter. The plugin's configurator must extend `s9e\TextFormatter\Plugins\ConfiguratorBase` and doesn't have to implement any methods. Properties of the plugin's configurator are saved in its configuration. If some properties should not be saved, you need to filter them in by implementing `asConfig()`. If you implement a `setUp()` method it will be run once after the plugin is initialized.

The plugin's parser class must extend `s9e\TextFormatter\Plugins\ParserBase` and implement the `public function parse($text, array $matches)` method. Its configuration is available in `$this->config`, the main parser in `$this->parser`. If parser's class name is assumed to be the same as the configurator's except with "Parser" at the end instead of "Configurator". If that's not the case, the configurator must set it via the `className` config. If the configurator has a `regexp` property, the regexp will be run on the text and its matches will be passed in `$matches`. If there are no matches, the method won't be called. If you don't set a regexp, an empty array will be passed.

```php
class MyConfigurator extends s9e\TextFormatter\Plugins\ConfiguratorBase
{
	protected $str = 'abc';
	protected function setUp()
	{
		$this->configurator->tags->add('X')->attributes->add('value');
	}

//	protected $className = 'MyParser';
//	public function asConfig()
//	{
//		return parent::asConfig();
//	}
}

class MyParser extends s9e\TextFormatter\Plugins\ParserBase
{
	public function parse($text, array $matches)
	{
		$this->parser->addSelfClosingTag('X', 0, 0)->setAttribute('value', $this->config['str']);
	}
}

$configurator = new s9e\TextFormatter\Configurator;
$configurator->MyPlugin = new MyConfigurator($configurator);
extract($configurator->finalize());

echo $parser->parse(''), "\n";
```
```xml
<r><X value="abc"/></r>
```

**Comment by RikSomers** [comment]
Hi Joshy,

Thanks for the quick support again!

I would assume with this syntax I would also be able to override default plugins if i needed/wanted to? 

I really love the way this library works and I'm trying really hard to incorporate it into my project and extending it according to my projects private needs. So, it might again be a misunderstanding/misuse of your library on my part.

The use-cases I was thinking of were for example with changing (extending if you will) the autolinker and autoimager.

For the Autolinker I wanted to make it so it fetches the title of the page (if it's on my project's domain) and uses this as the TEXT attribute inside the anchor tag. This is especially useful when linking to blogposts or forum posts, as the users will be able to see quickly where the link is pointing to. This however might be better suited for postparsing (like with the Quote-alert I asked about a couple days ago). Am I correct in this assumption?

For the autoimager I wanted to be able to plug in a resizing, (and maybe caching / https camo) library. As (with testing) I found that people can link to arbitrarily large images, and the autoimager (to my knowledge) has no configuration as to how to display the image, or any customization at all for that matter. Another example is matching other filetypes besides gif, jpg and png.
Again, I'm not sure if this is better suited at postparsing, by going over all IMG tags and applying needed configuration, or by altering the default template of the img tag after the autoimager has parsed them?

Again, thanks for all your help already :)

- Rik

**Comment by JoshyPHP** [comment]
About replacing a link's text, post processing may be the correct way to do it because it will "stick" and it won't be undone if you edit the text later.

Otherwise, for a fully-dynamic solution you'd need to create a tag that represents the link's text and use a tag filter to add the tag during parsing. That's how phpBB 3.2 replaces (truncates) some URLs. You can take a look at the `phpbb\textformatter\s9e\factory::configure_autolink` method and `phpbb\textformatter\s9e\link_helper` class.

The Autoimage plugin uses the `IMG` tag. If you want to modify its template it's in `$configurator->tags['IMG']` or `$configurator->Autoimage->getTag()`. If you want Autoimage to use a different tag or a different regexp, you can set it when instantiating the plugin:

```php
$configurator->plugins->load(
	'Autoimage',
	[
		'regexp'  => '#http://\\S+#',
		'tagName' => 'MYIMG'
	]
);
```

**Comment by RikSomers** [comment]
Thanks. I'll close this issue then. I think I can work something out with the code you gave :)

**Comment by milindsingh** [comment]
@JoshyPHP @RikSomers I am Flarum and trying to override `PipeTables` in my extension by adding custom plugin.

I wanted to add few attributes to table td, but even though my plugin is loader in $plugins l, it's not used to parse and render table.

Can you guide whats missing?

**Comment by JoshyPHP** [comment]
@milindsingh [I created a discussion for it in the Support forum](https://github.com/s9e/TextFormatter/discussions/232). If it doesn't exactly fit your use case, reply with a specific description of what you're trying to achieve. I don't think I have a working Flarum right now so ideally you would write it as a proof-of-concept that works independently from it.
