### ISSUE TITLE
Roadmap to 1.0?

### ISSUE THREAD

**Issue by tobscure** [s9e/TextFormatter#61]
Hey @JoshyPHP! Just curious if you have any plans for a 1.0 release (guarantee no breaking API changes) in the future?

Asking because it may have implications on a 1.0 release for Flarum, since we need to guarantee to our extension developers that nothing will break, and so we'd effectively be stuck with whatever 0.x TextFormatter version we release with. 

Thanks so much for your hard work with this library! It's a testament that it's one of the parts of Flarum that I have to think about the least, because it's so seamless and it just works™ :)

**Comment by JoshyPHP** [comment]
It took me a while to reply because it's hard for me to answer this question without rambling.

There are two parts to this: version numbers and API freeze. [Version numbers](https://en.wikipedia.org/wiki/Software_versioning) have no intrinsic meaning; Donald Knuth uses π and e, some people use semantic versioning and others think and/or say they use semantic versioning but they still make API changes in minor versions. As far as this library is concerned, I use [semantic versioning](http://semver.org/), which means that I'll bump the version number every time a method signature's changes in a backward-incompatible way.

That brings me to the API freeze part. The API has been pretty stable for some time and I started documenting [API changes](http://s9etextformatter.readthedocs.io/Internals/API_changes/) in 0.7.0, released in September 2016. Apart from removing the method that was deprecated in 0.7.0 (which will happen in 0.10.0) I have no API changes planned for the forseeable future. The only thing that has kept me from declaring the current master one-point-oh-worthy is that I want to spin some of the library (especially things related to regexps and XSLT) into their own subprojects. However, I can't do that while maintaining compatibility with PHP 5.5. s9e\TextFormatter is only compatible with PHP 5.3-5.5 via automated source patching, a custom method that does not scale well to multiple projects.

The takeaway is this:

 - The library uses semantic versioning and whenever I say "API" I mean any public method from any class, whether or not it's intended to be used publicly..
 - The API has been stable long enough that I'm thinking about bumping the version number to 1.0.0 to indicate that.
 - There *will* be API changes after 1.x. I don't think there will be a 2.0 this year but it's not entirely impossible.
 - API changes are manually documented in [docs/Internal/API_changes.md](http://s9etextformatter.readthedocs.io/Internals/API_changes/). The descriptions are intentionally kept as short and concise as possible so that it only takes a glance to know whether a change affects you.
 - Future changes are expected to be small and on subsystems that you don't use.
 - I will bump the PHP requirements from 5.3 to 5.6 or 7.0 at some point in the future, but with phpBB 3.2's requirements set to PHP 5.4 and Flarum's to PHP 5.5, it's not going to happen soon.

I hope that addresses most of it. :+1:

**Comment by franzliedke** [comment]
Thanks for the detailed response. :+1:

Just to let you know: It is very likely that we will raise the required minimum PHP version for Flarum to PHP 5.6 before the final release as well.

**Comment by JoshyPHP** [comment]
For reference, there's a [1.0 milestone](https://github.com/s9e/TextFormatter/milestone/3) scheduled for Jan 1st, 2018. v0.12 will be released soon and after that there is no big change planned before 1.0.
