### ISSUE TITLE
Alias HTML elements to other tags with rules on content

### ISSUE THREAD

**Issue by beavis** [s9e/TextFormatter#69]
First of all, thanks for this awesome library :)
I'm having troubles with aliasing elements when there are rules present on the content.
`$configurator->HTMLElements->aliasElement('kbd', 'KBD');`
For example having this tag definition alias works:
```
<bbcode name="KBD">
    <usage>[KBD]{TEXT}[/KBD]</usage>
    <template><![CDATA[
        <kbd class="foo">{TEXT}</kbd>
    ]]></template>
</bbcode>
```
While this one does not  (tag gets invalidated when filtering attributes)
```
<bbcode name="KBD">
    <usage>[KBD]{SIMPLETEXT}[/KBD]</usage>
    <template><![CDATA[
        <kbd class="foo">{SIMPLETEXT}</kbd>
    ]]></template>
</bbcode>
```

Am I missing something? Tried to alias the "content" attribute on the tag too but it doesn't seem to work that way.
Thanks!

**Comment by JoshyPHP** [comment]
Can you provide a small reproducible script that shows the issue? You can use [this](http://s9etextformatter.readthedocs.io/Plugins/HTMLElements/Aliases/) as a template. You don't have to comment it.

**Comment by JoshyPHP** [comment]
Ok, actually I know what's going on. Because its content requires validation, the second BBCode is interpreted as something like this:

```
[KBD content={SIMPLETEXT;useContent}]{SIMPLETEXT}[/KBD]
```

The content is copied to an attribute then filtered. For instance, the following would be equivalent:

```
[kbd]foo[/kbd]
[kbd content=foo]
```

That's part of the BBCode plugin, but that's not something the HTML plugin does. That's why the HTML version will fail; it creates a tag without setting the `content` attribute and the tag is invalidated because of the missing attribute. I'm not sure you can have validation on content on an HTML element.

**Comment by beavis** [comment]
Yeah the only reason for this is I want to restrict the content via regexp (since it represents keyboard input) and tried to do it via HTML since it seemed like the cleanest way.
I see that naming the Preg as the bbcode works just like aliasing them, awesome. 
Thanks for the quick help :)
