### ISSUE TITLE
Access to TextFormatter's Emoji map

### ISSUE THREAD

**Issue by tobscure** [s9e/TextFormatter#81]
Currently in Flarum's emoji extension, we include [our own map](https://github.com/flarum/flarum-ext-emoji/blob/master/js/forum/src/helpers/emojiMap.js) of shortcodes. I'm not sure where we got this from, but apparently there are a few inconsistencies between it and TextFormatter's supported shortcodes.

Copy+pasting TextFormatter's map into that file is easy enough, but I was wondering if there's a way to use the map the TextFormatter spits out in its JS directly? That way we wouldn't need to worry about any changes in the future.

**Comment by JoshyPHP** [comment]
That makes sense. I'm going to think about it.

Plugin parsers are defined and run inside of a closure so at the moment there's no way for any plugin to touch the global scope without running the parser first and doing something like `window['x']=x`.

**Comment by JoshyPHP** [comment]
Ok, so I thought about it and there's no clean way to make that map available outside of its scope. Coincidentally, I've just realized something: those maps are actually useless. For one, they keep growing with every Unicode release. With skin/gender modifiers, each new emoji can add more than a dozen new entries, and  nobody actually types them. Since they are only used in emoji selectors, why not use the sequence of codepoints instead? For instance, instead of adding `:man_in_business_suit_levitating_tone1:` to a post, add `:1f574-1f3fb:`. *(there's no support for that form at the moment)*

Of course, dropping the map causes some issues with backward compatibility (only if a post is reparsed) but going forward I think that's the way to go. The map in Flarum is 50 KB, the one in this library weighs 90 KB and it will only keep increasing.

I'm closing this issue because I don't think the map will ever be available outside of its scope but I'm open for input on getting rid of those maps altogether.

**Comment by tobscure** [comment]
So you're suggesting to get rid of the human-friendly shortcodes from TextFormatter altogether, and leave it up to the app to implement their own human-friendly shortcode selector?

So in Flarum when you start typing `:man_in` or whatever, we would include our own map which suggests `man_in_business_suit_levitating_tone1`. And if you select that and press Enter, it would insert `:1f574-1f3fb:` into the textarea (or you could even just insert the emoji character itself 🕴🏻, like GitHub comments do?) which TextFormatter would then be able to convert into EmojiOne. 

Have I got that right?

**Comment by JoshyPHP** [comment]
Yes. I still have to figure out some of it because I only came to this conclusion (getting rid of maps) as I was writing the previous comment, but that's the gist.

I realized that while some people may use short codes such as `:pizza:`, nobody ever types `:woman_construction_worker_tone3:`. Whenever this is entered in a text, it comes from an emoji selector of sorts, and if the emoji selector doesn't use the same list of codes as the underlying library you end with mismatched or non-working codes as you described above. By leaving the emoji selector in charge of the selection of codepoints by sending either the actual Unicode characters or their ASCII representation, you guarantee that the preview from the emoji selector matches the result.

The map current map is based on gemoji and EmojiOne's maps. From what I can tell, they are based off Apple's glyph names from the emoji font.

 * https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json
 * https://raw.githubusercontent.com/Ranks/emojione-assets/master/emoji.json

For your own selector, you may want to look into Unicode's data directly:

 * http://www.unicode.org/Public/emoji/latest/emoji-test.txt
 * http://unicode.org/repos/cldr/tags/latest/common/annotations/en.xml

**Comment by franzliedke** [comment]
IMO, seeing `:1f574-1f3fb:` even instead of `:man_in_business_suit_levitating_tone1` would be problematic in terms of user-friendliness. Confusing and inconsistent.

Not to point any fingers, but I think this should be solved on the library level.

On the other hand, maybe this problem exists only because Flarum's emoji selector is completely based on text input. When you can't search by these stranger ones, but instead select them from a long list of images, then a strange code would at least not be super-surprising.

**Comment by franzliedke** [comment]
Still, making it possible to remember the shortcodes (maybe with some help from the selector) is a big feature.

**Comment by JoshyPHP** [comment]
Note that even if the map is removed you can [add your own aliases](http://s9etextformatter.readthedocs.io/Plugins/Emoji/Configuration/#add-aliases-to-emoji).

About user-friendliness, one solution is to use the emoji itself. Shortcodes are less consistent than using codepoints directly. There's no standard for shortcodes; The ones from EmojiOne have occasionally changed from one release to another and those that exist today suffer from [small inconsistencies](https://github.com/emojione/emojione/issues/499).

**Comment by tobscure** [comment]
> About user-friendliness, one solution is to use the emoji itself.

This is what GitHub does, I like this 🕴

**Comment by JoshyPHP** [comment]
I'm currently planning an update to the Emoji plugin. I'm optimistically aiming for a 1.3.0 release in September. The current plan is to remove the inaccessible map from the parser and move it to the configurator as an accessible property. For example:

```php
$configurator->Emoji->shortnames = [
    '+1' => "\u{1f44d}",
    '-1' => "\u{1f44e}",
    // ...
];
```

The public API will remain compatible, the current map will remain in 1.x and will likely be removed in a future 2.x release.
