### ISSUE TITLE
MediaEmbed JS Loading Block Render page

### ISSUE THREAD

**Issue by TarantinoMariachi** [s9e/TextFormatter#90]
Hi there, after installed the MediaEmbed phpbb extension, I've got some js issues.
Sometimes the browser is not loading all the .js, and I've found out that everytime there is something on a post like an youtube video, the probability of the page fail to render properly is higher.

How can I defer the js so it can load after page well rendered?

**Comment by JoshyPHP** [comment]
I assume you're talking about the "phpBB Media Embed PlugIn" extension, which I'm not familiar about apart from the fact that it uses the default definitions from this library. The only JavaScript contained in this library executes when iframes hosted on GitHub are loaded. There's no JavaScript related to YouTube.

If you can provide some way to describe and reproduce the issue using only this library, I'll look into it. Otherwise, I assume it's unrelated and/or outside of my control.
