### ISSUE TITLE
Composer warnings

### ISSUE THREAD

**Issue by franzliedke** [s9e/TextFormatter#98]
When running `composer validate --no-check-all --strict`, I get the following warnings:

~~~
The version field is present, it is recommended to leave it out if the package is published on Packagist.
php is required both in require and require-dev, this can lead to unexpected behavior
~~~

**Comment by JoshyPHP** [comment]
I looked into those warnings and as far as I can tell they are general recommendations that can be ignored. The thing about omitting the [version number](https://getcomposer.org/doc/04-schema.md#version) is meant to prevent human errors related to Git tags and doesn't apply here because version tags are never created manually. I'll consider removing the version number from the release branch if it has any benefits but I'm wary of the potential side effects.

I removed the PHP requirement from `require-dev` because it's only useful in the master branch and doesn't need to appear in the release branch.

I'm closing this for now, feel free to reopen if you find that version numbers cause issues in Composer.
